=== VHDLTool/VHDL_Handbook_Toolchain/src/XSD/handbook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="HANDBOOK" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" xmlns:hb="HANDBOOK">


<!-- ======================= -->
<!--    Element definition   -->
<!-- ======================= -->
	<xs:element name="RuleSet" type="hb:TRuleSet"/>

<!-- ======================= -->
<!-- Complex type definition -->
<!-- ======================= -->
	<xs:complexType name="TRuleSet">
		<xs:sequence>
			<xs:element name="Rule" type="hb:TRule" maxOccurs="unbounded" minOccurs="1"/>
			<xs:element name="RuleSetHist" type="hb:TRuleSetHist" maxOccurs="1" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TRuleSetHist">
		<xs:sequence>
			<xs:element name="Version" type="xs:positiveInteger" maxOccurs="1" minOccurs="1"/>
			<xs:element name="Creation" type="xs:date" maxOccurs="1" minOccurs="1"/>
			<xs:element name="Modified" type="xs:date" maxOccurs="1" minOccurs="1"/>
			<xs:element name="Revision" type="xs:string" maxOccurs="1" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TRule">
		<xs:sequence>
			<xs:element name="RuleUID" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:ID">
						<xs:pattern value="[A-Z]{3}_[0-9]{5}" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="RuleHist" type="hb:TRuleHist"	maxOccurs="1" minOccurs="1"/>
			<xs:element name="RuleContent" type="hb:TRuleContent" maxOccurs="1" minOccurs="1"/>
			<xs:element name="RuleDesc" type="hb:TRuleDesc"	maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="UID" type="hb:TRuleUID"/>
	</xs:complexType>

	<xs:complexType name="TRuleHist">
		<xs:sequence>
			<xs:element name="Status" type="hb:EnumRuleStatus" maxOccurs="1" minOccurs="1"/>
			<xs:element name="Version" type="xs:positiveInteger" maxOccurs="1" minOccurs="1"/>
			<xs:element name="Creation" type="xs:date" maxOccurs="1" minOccurs="1"/>
			<xs:element name="Modified" type="xs:date" maxOccurs="1" minOccurs="1"/>
			<xs:element name="Revision" type="xs:string" maxOccurs="1" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TRuleDesc">
		<xs:sequence>
			<xs:element name="GoodExDesc" type="xs:string" maxOccurs="1" minOccurs="1" nillable="true"/>
			<xs:element name="GoodExample" type="xs:string"	maxOccurs="1" minOccurs="1" nillable="true"/>
			<xs:element name="BadExDesc" type="xs:string" maxOccurs="1"	minOccurs="1" nillable="true"/>
			<xs:element name="BadExample" type="xs:string" maxOccurs="1" minOccurs="1" nillable="true"/>
			<xs:element name="FigureDesc" type="xs:string" maxOccurs="1" minOccurs="1" nillable="true"/>
			<xs:element name="Figure" type="hb:TFigure" maxOccurs="1" minOccurs="1" nillable="true"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TFigure">
		<xs:attribute name="fileref" type="xs:anySimpleType"/>
		<xs:attribute name="height" type="xs:string"/>
		<xs:attribute name="width" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="TRuleContent">
		<xs:sequence>
			<xs:element name="Name" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="IsParent" type="xs:boolean" maxOccurs="1" minOccurs="1"/>
            <xs:element name="IsSon" type="xs:boolean" maxOccurs="1" minOccurs="1"/>
            <xs:element name="ParentUID" type="hb:TRuleUID" maxOccurs="1" minOccurs="1" nillable="true"/>
			<xs:element name="Technology" type="hb:EnumTech" maxOccurs="1" minOccurs="1"/>
			<xs:element name="ApplicationFields" type="hb:ListAppliFields" maxOccurs="1" minOccurs="1"/>
			<xs:element name="Category" type="hb:EnumCat" maxOccurs="1"	minOccurs="1"/>
			<xs:element name="SubCategory" type="hb:EnumSubCat"	maxOccurs="1" minOccurs="1"/>
			<xs:element name="Severity" type="hb:EnumSeverity" maxOccurs="1" minOccurs="1"/>
			<xs:element name="Rationale" type="xs:string" maxOccurs="1"	minOccurs="1"/>
			<xs:element name="ShortDesc" type="xs:string" maxOccurs="1"	minOccurs="1"/>
			<xs:element name="LongDesc" type="xs:string" maxOccurs="1" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
<!-- ======================= -->
<!-- Simple type definition  -->	
<!-- ======================= -->

	<xs:simpleType name="TRuleUID">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{3}_[0-9]{5}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="EnumRuleStatus">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Draft"/>
			<xs:enumeration value="In progress"/>
			<xs:enumeration value="Release candidate"/>
			<xs:enumeration value="Validated"/>
			<xs:enumeration value="Rejected"/>
			<xs:enumeration value="Active"/>
			<xs:enumeration value="Deleted"/>
			<xs:enumeration value="To be discussed"/>
			<xs:enumeration value="Modified"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="EnumTech">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FPGA"/>
			<xs:enumeration value="ASIC"/>
			<xs:enumeration value="VLSI"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="EnumCat">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Traceability"/>
			<xs:enumeration value="Formatting"/>
			<xs:enumeration value="Design"/>
			<xs:enumeration value="Simulation"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="EnumSubCat">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Versioning"/>
			<xs:enumeration value="Reuse"/>
			<xs:enumeration value="Requirement"/>
			<xs:enumeration value="Miscellaneous"/>
			<xs:enumeration value="Naming"/>
			<xs:enumeration value="FileStructure"/>
			<xs:enumeration value="StateMachine"/>
			<xs:enumeration value="Reset"/>
			<xs:enumeration value="Clocking"/>
			<xs:enumeration value="I/O"/>
			<xs:enumeration value="Synchronous"/>
			<xs:enumeration value="Combinational"/>
			<xs:enumeration value="Type"/>
			<xs:enumeration value="Reliability"/>	
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="EnumSeverity">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Note"/>
			<xs:enumeration value="Minor"/>
			<xs:enumeration value="Major"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="ListAppliFields">
		<xs:list itemType="hb:EnumAppliFieds"/>
	</xs:simpleType>

	<xs:simpleType name="EnumAppliFieds">
		<xs:restriction base="xs:string">
			<xs:enumeration value="General"/>
			<xs:enumeration value="Spatial"/>
			<xs:enumeration value="Avionic"/>
			<xs:enumeration value="Nuclear"/>
			<xs:enumeration value="Railway"/>
			<xs:enumeration value="Defense"/>
			<xs:enumeration value="Telecom"/>
			<xs:enumeration value="Media"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== VHDLTool/VHDL_Handbook_Toolchain/src/RuleSets/handbook_STD.xml
<?xml version="1.0" encoding="UTF-8"?>
<hb:RuleSet xmlns:hb="HANDBOOK"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="HANDBOOK ../XSD/handbook.xsd ">

	<hb:Rule UID="STD_00600">
		<hb:RuleUID>STD_00600</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Validated</hb:Status>
			<hb:Version>3</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2015-02-17</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
			   V2 : 2014-12-01 : Technology ; Rationale
            V3 : 2015-02-17 : Severity
         </hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>VHDL file extension</hb:Name>
			<hb:IsParent>false</hb:IsParent>
			<hb:IsSon>false</hb:IsSon>
			<hb:ParentUID xsi:nil="true" />
			<hb:Technology>VLSI</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Formatting</hb:Category>
			<hb:SubCategory>Naming</hb:SubCategory>
			<hb:Severity>Minor</hb:Severity>
			<hb:Rationale>Same extension for each source file improves search and scripted automated actions.</hb:Rationale>
			<hb:ShortDesc>The extension of VHDL source file is .vhd</hb:ShortDesc>
			<hb:LongDesc>The extension of the VHDL file is ".vhd". The extension ".v" is reserved for the Verilog language. 
The extension ".vhdl" is not permitted.</hb:LongDesc>
		</hb:RuleContent>
		<hb:RuleDesc>
			<hb:GoodExDesc />
			<hb:GoodExample />
			<hb:BadExDesc />
			<hb:BadExample />
			<hb:FigureDesc />
			<hb:Figure />
		</hb:RuleDesc>
	</hb:Rule>
	
	<hb:Rule UID="STD_00800">
		<hb:RuleUID>STD_00800</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Validated</hb:Status>
			<hb:Version>3</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2015-02-17</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
				V2 : 2014-12-01 : Technology ; Rationale
				V3 : 2015-02-17 : Severity
			</hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>File name convention</hb:Name>
			<hb:IsParent>true</hb:IsParent>
			<hb:IsSon>false</hb:IsSon>
			<hb:ParentUID xsi:nil="true" />
			<hb:Technology>VLSI</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Formatting</hb:Category>
			<hb:SubCategory>Naming</hb:SubCategory>
			<hb:Severity>Minor</hb:Severity>
			<hb:Rationale>File name coherence improves search and scripted automated actions.</hb:Rationale>
			<hb:ShortDesc>File name uses an unique and specific naming convention within a design.</hb:ShortDesc>
			<hb:LongDesc>No additional information.</hb:LongDesc>
		</hb:RuleContent>
		<hb:RuleDesc>
			<hb:GoodExDesc />
			<hb:GoodExample />
			<hb:BadExDesc />
			<hb:BadExample />
			<hb:FigureDesc />
			<hb:Figure />
		</hb:RuleDesc>
	</hb:Rule>
	
	<hb:Rule UID="STD_00900">
		<hb:RuleUID>STD_00900</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Validated</hb:Status>
			<hb:Version>3</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2015-02-17</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
				V2 : 2014-12-01 : Technology ; Rationale ; LongDesc ; GoodExDesc ; BadExDesc
				V3 : 2015-02-17 : Severity
			</hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>File name of an entity</hb:Name>
			<hb:IsParent>false</hb:IsParent>
			<hb:IsSon>true</hb:IsSon>
			<hb:ParentUID>STD_00800</hb:ParentUID>
			<hb:Technology>VLSI</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Formatting</hb:Category>
			<hb:SubCategory>Naming</hb:SubCategory>
			<hb:Severity>Minor</hb:Severity>
			<hb:Rationale>The match between file name and entity name improves the search for an entity inside a project.</hb:Rationale>
			<hb:ShortDesc>The file name for an entity VHDL file includes at least the entity name.</hb:ShortDesc>
			<hb:LongDesc>File name of an entity called MyEntity is :
			
				(Any characters)MyEntity(Any characters).vhd</hb:LongDesc>
		</hb:RuleContent>
		<hb:RuleDesc>
			<hb:GoodExDesc />
			<hb:GoodExample />
			<hb:BadExDesc />
			<hb:BadExample />
			<hb:FigureDesc />
			<hb:Figure />
		</hb:RuleDesc>
	</hb:Rule>
	
	<hb:Rule UID="STD_00100">
		<hb:RuleUID>STD_00100</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Validated</hb:Status>
			<hb:Version>2</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2014-12-01</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
				V2 : 2014-12-01 : Technology ; Rationale ; ShortDesc
			</hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>VHDL object naming convention</hb:Name>
			<hb:IsParent>true</hb:IsParent>
			<hb:IsSon>false</hb:IsSon>
			<hb:ParentUID xsi:nil="true" />
			<hb:Technology>VLSI</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Formatting</hb:Category>
			<hb:SubCategory>Naming</hb:SubCategory>
			<hb:Severity>Major</hb:Severity>
			<hb:Rationale>VHDL Object naming convention improves readability and reuse.</hb:Rationale>
			<hb:ShortDesc>VHDL Object name definition uses an unique and specific naming convention.</hb:ShortDesc>
			<hb:LongDesc>This convention can address the naming of any VHDL objects like signals, variables, constants, generic, labels, modules, entity, etc.</hb:LongDesc>
		</hb:RuleContent>
		<hb:RuleDesc>
			<hb:GoodExDesc />
			<hb:GoodExample />
			<hb:BadExDesc />
			<hb:BadExample />
			<hb:FigureDesc />
			<hb:Figure />
		</hb:RuleDesc>
	</hb:Rule>
	
	<hb:Rule UID="STD_00200">
		<hb:RuleUID>STD_00200</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Validated</hb:Status>
			<hb:Version>4</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2015-07-16</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
				V2 : 2014-12-01 : Technology ; Rationale ; LongDesc
				V3 : 2015-02-17 : ShortDesc ; LongDesc ; FigureDesc
				V4 : 2015-07-16 : GoodExample ; GoodExDesc 
			</hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>Name of clock signal</hb:Name>
			<hb:IsParent>false</hb:IsParent>
			<hb:IsSon>true</hb:IsSon>
			<hb:ParentUID>STD_00100</hb:ParentUID>
			<hb:Technology>VLSI</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Formatting</hb:Category>
			<hb:SubCategory>Naming</hb:SubCategory>
			<hb:Severity>Major</hb:Severity>
			<hb:Rationale>The clock signal is critical. This signal needs to be easily found through the design.</hb:Rationale>
			<hb:ShortDesc>The clock signal name includes "clk" or "clock".</hb:ShortDesc>
			<hb:LongDesc>A signal is considered as a "CLOCK" whenever it is used to synchronize other signals to its rising or falling edge within a synchronous process with one of the following VHDL functions ('event, rising_edge or falling_edge), or when it is mapped on an IP clock input.</hb:LongDesc>
		</hb:RuleContent>
		<hb:RuleDesc>
			<hb:GoodExDesc>Extracted from STD_00200_good.vhd</hb:GoodExDesc>
			<hb:GoodExample >STD_00200_good</hb:GoodExample>
			<hb:BadExDesc></hb:BadExDesc>
			<hb:BadExample ></hb:BadExample>
			<hb:FigureDesc />
			<hb:Figure ></hb:Figure>
		</hb:RuleDesc>
	</hb:Rule>
	
	<hb:Rule UID="STD_00300">
		<hb:RuleUID>STD_00300</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Validated</hb:Status>
			<hb:Version>5</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2015-11-18</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
				V2 : 2014-12-01 : Technology ; Rationale ; LongDesc
				V3 : 2015-02-17 : ShortDesc ; FigureDesc
				V4 : 2015-07-16 : GoodExample ; GoodExDesc
				V5 : 2015-11-18 : LongDesc
			</hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>Name of reset signal</hb:Name>
			<hb:IsParent>false</hb:IsParent>
			<hb:IsSon>true</hb:IsSon>
			<hb:ParentUID>STD_00100</hb:ParentUID>
			<hb:Technology>VLSI</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Formatting</hb:Category>
			<hb:SubCategory>Naming</hb:SubCategory>
			<hb:Severity>Major</hb:Severity>
			<hb:Rationale>The reset signal is critical. This signal needs 
			to be easily found through the design.</hb:Rationale>
			<hb:ShortDesc>The reset signal name includes "rst", "reset" or "clr".</hb:ShortDesc>
			<hb:LongDesc>A signal is considered as a "RESET" whenever it is used inside a clocked-process to initialize signals value to a known state (most of the time zero) or mapped on a IP reset input.
If several reset signals are used, each reset is identified with a different name.</hb:LongDesc>
		</hb:RuleContent>
		<hb:RuleDesc>
			<hb:GoodExDesc>Extracted from STD_00300_good.vhd</hb:GoodExDesc>
			<hb:GoodExample >STD_00300_good</hb:GoodExample>
			<hb:BadExDesc></hb:BadExDesc>
			<hb:BadExample ></hb:BadExample>
			<hb:FigureDesc />
			<hb:Figure />
		</hb:RuleDesc>
	</hb:Rule>
	
	<hb:Rule UID="STD_00400">
		<hb:RuleUID>STD_00400</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Validated</hb:Status>
			<hb:Version>3</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2015-07-16</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
				V2 : 2014-12-01 : Technology ; Rationale
				V3 : 2015-07-16 : GoodExample ; BadExample ; GoodExDesc ; BadExDesc
			</hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>Label for process</hb:Name>
			<hb:IsParent>false</hb:IsParent>
			<hb:IsSon>true</hb:IsSon>
			<hb:ParentUID>STD_00100</hb:ParentUID>
			<hb:Technology>VLSI</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Formatting</hb:Category>
			<hb:SubCategory>Naming</hb:SubCategory>
			<hb:Severity>Minor</hb:Severity>
			<hb:Rationale>Labels improve readability of simulations, VHDL source code and synthesis logs.</hb:Rationale>
			<hb:ShortDesc>Processes are identified by a label.</hb:ShortDesc>
			<hb:LongDesc>No additional information.</hb:LongDesc>
		</hb:RuleContent>
		<hb:RuleDesc>
			<hb:GoodExDesc>Extracted from STD_00400_good.vhd</hb:GoodExDesc>
			<hb:GoodExample >STD_00400_good</hb:GoodExample>
			<hb:BadExDesc>Extracted from STD_00400_bad.vhd</hb:BadExDesc>
